/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericErrorModel,
  GetTags200Response,
} from '../models/index';
import {
    GenericErrorModelFromJSON,
    GenericErrorModelToJSON,
    GetTags200ResponseFromJSON,
    GetTags200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class TagsApi extends runtime.BaseAPI {

    /**
     * Get tags. Auth not required
     * Get tags
     */
    async getTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTags200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tags`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTags200ResponseFromJSON(jsonValue));
    }

    /**
     * Get tags. Auth not required
     * Get tags
     */
    async getTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTags200Response> {
        const response = await this.getTagsRaw(initOverrides);
        return await response.value();
    }

}
