/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTags200Response
 */
export interface GetTags200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetTags200Response
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the GetTags200Response interface.
 */
export function instanceOfGetTags200Response(value: object): boolean {
    if (!('tags' in value)) return false;
    return true;
}

export function GetTags200ResponseFromJSON(json: any): GetTags200Response {
    return GetTags200ResponseFromJSONTyped(json, false);
}

export function GetTags200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTags200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'],
    };
}

export function GetTags200ResponseToJSON(value?: GetTags200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tags': value['tags'],
    };
}

