/* tslint:disable */
/* eslint-disable */
/**
 * RealWorld Conduit API
 * Conduit API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewArticle
 */
export interface NewArticle {
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    body: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewArticle
     */
    tagList?: Array<string>;
}

/**
 * Check if a given object implements the NewArticle interface.
 */
export function instanceOfNewArticle(value: object): boolean {
    if (!('title' in value)) return false;
    if (!('description' in value)) return false;
    if (!('body' in value)) return false;
    return true;
}

export function NewArticleFromJSON(json: any): NewArticle {
    return NewArticleFromJSONTyped(json, false);
}

export function NewArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewArticle {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'body': json['body'],
        'tagList': json['tagList'] == null ? undefined : json['tagList'],
    };
}

export function NewArticleToJSON(value?: NewArticle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'body': value['body'],
        'tagList': value['tagList'],
    };
}

